import { useState, useEffect } from 'react';
import './App.css';
import SubscriptionList from './components/SubscriptionList';
import SubscriptionForm from './components/SubscriptionForm';
import CostSummary from './components/CostSummary';
import AnalyticsDashboard from './components/AnalyticsDashboard'; // Import AnalyticsDashboard

const API_URL = 'http://localhost:3001/subscriptions'; // Backend API URL

function App() {
  const [subscriptions, setSubscriptions] = useState([]);
  const [editingSubscription, setEditingSubscription] = useState(null); // null or subscription object
  const [showForm, setShowForm] = useState(false);

  // Fetch subscriptions from backend
  const fetchSubscriptions = async () => {
    try {
      const response = await fetch(API_URL);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const data = await response.json();
      setSubscriptions(data);
    } catch (error) {
      console.error("Failed to fetch subscriptions:", error);
      // Handle error (e.g., show a message to the user)
    }
  };

  useEffect(() => {
    fetchSubscriptions();
  }, []);

  const handleAddSubscription = async (subscription) => {
    try {
      const response = await fetch(API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(subscription),
      });
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      // const newSubscription = await response.json(); // No need to use if fetchSubscriptions is called
      fetchSubscriptions(); // Re-fetch to get the ID generated by backend
      setShowForm(false);
    } catch (error) {
      console.error("Failed to add subscription:", error);
    }
  };

  const handleUpdateSubscription = async (subscription) => {
    try {
      const response = await fetch(`${API_URL}/${subscription.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(subscription),
      });
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      fetchSubscriptions(); // Re-fetch
      setEditingSubscription(null);
      setShowForm(false);
    } catch (error) {
      console.error("Failed to update subscription:", error);
    }
  };

  const handleDeleteSubscription = async (id) => {
    if (!window.confirm("Are you sure you want to delete this subscription?")) {
        return;
    }
    try {
      const response = await fetch(`${API_URL}/${id}`, {
        method: 'DELETE',
      });
      if (!response.ok && response.status !== 204) { // 204 No Content is a success
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      fetchSubscriptions(); // Re-fetch
    } catch (error) {
      console.error("Failed to delete subscription:", error);
    }
  };

  const handleEdit = (subscription) => {
    setEditingSubscription(subscription);
    setShowForm(true);
  };

  const handleCancelEdit = () => {
    setEditingSubscription(null);
    setShowForm(false);
  };

  const handleShowAddForm = () => {
    setEditingSubscription(null);
    setShowForm(true);
  }

  return (
    <div className="app-container">
      <header>
        <h1>Subscription Tracker</h1>
      </header>
      <main>
        {!showForm && (
          <button onClick={handleShowAddForm} className="btn btn-primary add-new-btn">
            Add New Subscription
          </button>
        )}
        {showForm && (
          <SubscriptionForm
            onSave={editingSubscription ? handleUpdateSubscription : handleAddSubscription}
            onCancel={handleCancelEdit}
            existingSubscription={editingSubscription}
          />
        )}
        <CostSummary subscriptions={subscriptions} /> {/* Add CostSummary component */}
        <SubscriptionList
          subscriptions={subscriptions}
          onEdit={handleEdit}
          onDelete={handleDeleteSubscription}
        />
        <AnalyticsDashboard subscriptions={subscriptions} /> {/* Add AnalyticsDashboard */}
      </main>
      <footer>
        <p>&copy; 2024 Subscription Tracker App</p>
      </footer>
    </div>
  );
}

export default App;
